version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: its-users-postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: its_users
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
